apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-test-app
spec:
  destination:
    name: ''
    namespace: test-gitops
    server: https://kubernetes.default.svc
  source:
    path: manifests
    repoURL: https://github.com/diegofernandezpedroche/my-argocd-vault-example.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
