apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-test-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/diegofernandezpedroche/my-argocd-vault-example.git
    path: manifests
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_TYPE
          value: azurekeyvault
        - name: AVP_AUTH_TYPE
          value: clientsecret
        - name: AVP_AZUREKEYVAULT_NAME
          value: azr-we-kv-gb-ocptest-int
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: vault-configuration
              key: AZURE_TENANT_ID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: vault-configuration
              key: AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: vault-configuration
              key: AZURE_CLIENT_SECRET
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
